/**
 * Isolated proxy runtime for the netlab.
 *
 * The proxy resolves config/data/bin relative to process.cwd() (Electron
 * sets these explicitly; CLI mode defaults to cwd). So an isolated test
 * instance = its own directory:
 *
 *   tests/netlab/runtime/
 *     config/    ← copy of the repo config (default.yaml, fingerprint.yaml,
 *                  models.yaml, …) — fingerprint.yaml carries the upstream
 *                  Accept-Encoding header this lab measures
 *     data/      ← generated: local.yaml (port + api key), api-keys.json
 *                  (one upstream entry, wire "codex-responses" → native
 *                  rustls transport → the path under test), proxy.log
 *     native/    ← junction to the repo native/ (rustls addon)
 *
 * The proxy is spawned as `node tsx <repo>/src/index.ts` with cwd=runtime —
 * bare imports resolve from the entry file upward into the repo's
 * node_modules, while config/data land in the runtime dir.
 */

import {
  spawn, spawnSync,
} from "node:child_process";
import {
  cpSync, existsSync, mkdirSync, mkdtempSync, openSync,
  readFileSync, rmSync, statSync, symlinkSync, writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..", "..");
// Keep the runtime OUTSIDE the repo tree: it contains junctions and generated
// files, and repo-wide file walkers (e.g. boundary tests) must never see them.
let RUNTIME = null;
function ensureRuntimeDir() {
  if (!RUNTIME) RUNTIME = mkdtempSync(path.join(tmpdirBase(), "codex-netlab-"));
  return RUNTIME;
}
function tmpdirBase() {
  const base = path.join(os.tmpdir(), "netlab");
  mkdirSync(base, { recursive: true });
  return base;
}

export const PROXY_PORT = 8188;
export const PROXY_URL = `http://127.0.0.1:${PROXY_PORT}`;
export const PROXY_API_KEY = "netlab-dev-key";
export function runtimeDir() {
  return ensureRuntimeDir();
}

export const NETLAB_MODEL = "netlab-mock";
// Virtual upstream host: with tls.proxy_url pinned at the toxiproxy listener,
// reqwest never dials this host — it sends absolute-form requests through the
// "proxy" and the mock strips the scheme+host prefix on arrival.
export const MOCK_UPSTREAM_URL = "http://mock-upstream.test:9999";

const PROXY_LOG = () => path.join(runtimeDir(), "proxy.log");

let _child = null;
let _logOffset = 0;

/**
 * @typedef {object} StartProxyOptions
 * @property {number} [streamIdleTimeoutMs]  Override tls.stream_idle_timeout_ms
 *   in the runtime local.yaml (0 disables). Used by the stall scenario so the
 *   watchdog fires inside the client timeout instead of at the 120s default.
 */

/** @param {StartProxyOptions} [startOpts] */
function prepareDirs(startOpts = {}) {
  const dir = runtimeDir();
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(path.join(dir, "config"), { recursive: true });
  mkdirSync(path.join(dir, "data"), { recursive: true });

  // Static config — fingerprint.yaml matters most: it carries the upstream
  // Accept-Encoding: "gzip, deflate, br, zstd" header under test.
  cpSync(path.join(REPO, "config"), path.join(dir, "config"), { recursive: true });

  // Native rustls addon. Junction needs no admin on Windows; fall back to a
  // real copy of the loader + the current platform's .node binary.
  const nativeTarget = path.join(REPO, "native");
  const nativeLink = path.join(dir, "native");
  try {
    symlinkSync(nativeTarget, nativeLink, "junction");
  } catch {
    mkdirSync(nativeLink, { recursive: true });
    for (const f of ["index.js", "index.d.ts", "codex-tls.win32-x64-msvc.node"]) {
      cpSync(path.join(nativeTarget, f), path.join(nativeLink, f));
    }
  }

  writeFileSync(path.join(dir, "data", "local.yaml"), [
    "# Generated by tests/netlab — isolated runtime, do not edit by hand.",
    "server:",
    `  port: ${PROXY_PORT}`,
    `  proxy_api_key: "${PROXY_API_KEY}"`,
    "tls:",
    "  # Pin the upstream proxy at the toxiproxy listener (HTTP-proxy semantics,",
    "  # absolute-form). This both routes the upstream leg through the weak-net",
    "  # injection point and disables local-proxy auto-detection, which would",
    "  # otherwise hijack the leg to any running Clash/v2ray on this machine.",
    '  proxy_url: "http://127.0.0.1:28443"',
    ...(typeof startOpts.streamIdleTimeoutMs === "number"
      ? ["  # Per-scenario override — see StartProxyOptions.", `  stream_idle_timeout_ms: ${startOpts.streamIdleTimeoutMs}`]
      : []),
    "",
  ].join("\n"), "utf8");

  writeFileSync(path.join(dir, "data", "api-keys.json"), JSON.stringify({
    keys: [{
      id: "netlab-mock-1",
      provider: "custom",
      model: NETLAB_MODEL,
      apiKey: "netlab",
      baseUrl: MOCK_UPSTREAM_URL,
      label: "netlab-mock",
      wire: "codex-responses", // → CodexResponsesUpstream → native rustls transport
      status: "active",
      addedAt: new Date().toISOString(),
      lastUsedAt: null,
    }],
  }, null, 2), "utf8");
}

async function waitHealthy(url, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${url}/health`, { signal: AbortSignal.timeout(1500) });
      if (res.ok) return;
    } catch { /* not up yet */ }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`${url} did not become healthy within ${timeoutMs}ms`);
}

/** Prepare the runtime dir and start the proxy under test.
 *  @param {console} [logger]
 *  @param {StartProxyOptions} [startOpts]
 */
export async function startProxy(logger = console, startOpts = {}) {
  prepareDirs(startOpts);

  // tsx's package.json exports don't expose the CLI — use the file directly.
  const tsxCli = path.join(REPO, "node_modules", "tsx", "dist", "cli.mjs");
  const entry = path.join(REPO, "src", "index.ts");

  // Strip proxy env vars: the loader applies HTTPS_PROXY when no explicit
  // tls.proxy_url is configured, which would steer the upstream leg away
  // from the toxiproxy path under test.
  const env = { ...process.env };
  for (const k of ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"]) {
    delete env[k];
  }

  const logFd = openSync(PROXY_LOG(), "w");
  _child = spawn(process.execPath, [tsxCli, entry], {
    cwd: runtimeDir(),
    env,
    stdio: ["ignore", logFd, logFd],
    windowsHide: true,
  });
  _child.on("exit", (code) => {
    if (_child) logger.warn?.(`[proxy] exited code=${code}`);
    _child = null;
  });

  await waitHealthy(PROXY_URL, 60_000);
  logger.log(`[proxy] up at ${PROXY_URL} (runtime: ${runtimeDir()})`);
  _logOffset = existsSync(PROXY_LOG()) ? statSync(PROXY_LOG()).size : 0;
}

/** Stop the proxy under test. */
export async function stopProxy() {
  if (!_child) return;
  const child = _child;
  _child = null;
  child.kill();

  // Windows: node.kill() kills the direct child (tsx-in-process) only.
  if (process.platform === "win32") {
    spawnSync("taskkill", ["/PID", String(child.pid), "/T", "/F"], { windowsHide: true });
  }
  await new Promise((r) => setTimeout(r, 300));
}

/**
 * Proxy log lines appended since the previous call — used to attribute
 * premature-close / client-abort warnings to the scenario that caused them.
 */
export function proxyLogTail() {
  const logPath = PROXY_LOG();
  let size = 0;
  try { size = statSync(logPath).size; } catch { return ""; }
  if (size <= _logOffset) return "";
  // Slice as raw bytes (statSync size is byte-based), then decode — the log
  // contains multibyte UTF-8 (banner box chars), so a string slice would
  // silently misalign and drop everything.
  const tail = readFileSync(logPath).subarray(_logOffset).toString("utf8");
  _logOffset = size;
  return tail;
}
