import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--primary-hover) / <alpha-value>)",
        "primary-action": "rgb(var(--primary-action) / <alpha-value>)",
        "primary-action-hover": "rgb(var(--primary-action-hover) / <alpha-value>)",
        "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        "success-container": "rgb(var(--success-container) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        "warning-container": "rgb(var(--warning-container) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        "danger-container": "rgb(var(--danger-container) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        "info-container": "rgb(var(--info-container) / <alpha-value>)",
        "avatar-purple-text": "rgb(var(--avatar-purple-text) / <alpha-value>)",
        "avatar-purple-bg": "rgb(var(--avatar-purple-bg) / <alpha-value>)",
        "avatar-amber-text": "rgb(var(--avatar-amber-text) / <alpha-value>)",
        "avatar-amber-bg": "rgb(var(--avatar-amber-bg) / <alpha-value>)",
        "avatar-blue-text": "rgb(var(--avatar-blue-text) / <alpha-value>)",
        "avatar-blue-bg": "rgb(var(--avatar-blue-bg) / <alpha-value>)",
        "avatar-emerald-text": "rgb(var(--avatar-emerald-text) / <alpha-value>)",
        "avatar-emerald-bg": "rgb(var(--avatar-emerald-bg) / <alpha-value>)",
        "avatar-red-text": "rgb(var(--avatar-red-text) / <alpha-value>)",
        "avatar-red-bg": "rgb(var(--avatar-red-bg) / <alpha-value>)",
        "bg-light": "#f8fafc",
        "bg-dark": "rgb(13 17 23 / <alpha-value>)",
        "card-dark": "rgb(22 27 34 / <alpha-value>)",
        "border-dark": "rgb(48 54 61 / <alpha-value>)",
        "text-main": "rgb(230 237 243 / <alpha-value>)",
        "text-dim": "rgb(139 148 158 / <alpha-value>)",
      },
      fontFamily: {
        display: [
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "ui-monospace",
          "SFMono-Regular",
          "SF Mono",
          "Menlo",
          "Consolas",
          "Liberation Mono",
          "monospace",
        ],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
